import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col justify-between min-h-screen">
          <Navbar/>
          <div className="wrapper flex-1">
            {children}
          </div>
          <footer className='md:p-6 p-4 text-center bg-gray-100'>
            <p>&copy; 2024 QuickQuips. All rights reserved.</p>
          </footer>
          </div>
        </body>
    </html>
  );
}
